// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJze6cn7FaZ-dxkYPaHT49vu9_zfeq2kQ',
    appId: '1:341570401281:web:a83c7626cf01c9e158fc00',
    messagingSenderId: '341570401281',
    projectId: 'elmentor1-e1210',
    authDomain: 'elmentor1-e1210.firebaseapp.com',
    storageBucket: 'elmentor1-e1210.appspot.com',
    measurementId: 'G-M0TWEDZYS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJYS3DWRNuuY-t7vjlnyvdQ3mW7vrTbFk',
    appId: '1:341570401281:android:d84f3d849077764d58fc00',
    messagingSenderId: '341570401281',
    projectId: 'elmentor1-e1210',
    storageBucket: 'elmentor1-e1210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm2g5NVf_6xbetjNrn7FOb8DdBOSGi38c',
    appId: '1:341570401281:ios:abbbf872cbe156ac58fc00',
    messagingSenderId: '341570401281',
    projectId: 'elmentor1-e1210',
    storageBucket: 'elmentor1-e1210.appspot.com',
    iosBundleId: 'com.example.testslogreg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm2g5NVf_6xbetjNrn7FOb8DdBOSGi38c',
    appId: '1:341570401281:ios:abbbf872cbe156ac58fc00',
    messagingSenderId: '341570401281',
    projectId: 'elmentor1-e1210',
    storageBucket: 'elmentor1-e1210.appspot.com',
    iosBundleId: 'com.example.testslogreg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJze6cn7FaZ-dxkYPaHT49vu9_zfeq2kQ',
    appId: '1:341570401281:web:1572f9d79089096d58fc00',
    messagingSenderId: '341570401281',
    projectId: 'elmentor1-e1210',
    authDomain: 'elmentor1-e1210.firebaseapp.com',
    storageBucket: 'elmentor1-e1210.appspot.com',
    measurementId: 'G-WVZMVV9MTX',
  );
}
